name: xeno_canto_api_dart
description: A starting point for Dart libraries or applications.
version: 1.1.1
repository: https://github.com/igorskh/xeno_canto_api_dart

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  http: ^1.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0
  dotenv: ^4.2.0
  mockito: ^5.5.1
  build_runner: ^2.10.2
